title: Unlock the GPU
description: A developer-investor alliance working to break NVIDIA's CUDA monopoly by pressuring AMD to fix their software ecosystem
url: "https://unlockgpu.com"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "page"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Navigation
navigation:
  - title: Home
    url: /
  - title: FAQ
    url: /faq/
  - title: Priorities
    url: /priorities/
  - title: Activism Guide
    url: /activism/
  - title: Why $220M?
    url: /why220m/

# Social media
social:
  - name: GitHub
    url: https://github.com/yourusername/UnlockGPU
  - name: Twitter
    url: https://twitter.com/unlockgpu

# Theme settings
theme: minima 